// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/okyer/examples/gf4opengauss/api/demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: DemoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/add",
				Handler: addHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/delete/:id",
				Handler: deleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/list",
				Handler: listHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/update/:id",
				Handler: updateHandler(serverCtx),
			},
		},
	)
}
