// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type DelUser struct {
	Id int `path:"id"`
}

type ListUser struct {
	Name  string `json:"name,optional"`
	Email string `json:"email,optional"`
}

type ListUserResponse struct {
	Code    int           `json:"code"`
	Message string        `json:"message"`
	Data    []*UpdateUser `json:"data"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type UpdateUser struct {
	Id       int    `path:"id"`
	Name     string `json:"name"`
	Email    string `json:"email,optional"`
	Age      int    `json:"age"`
	Birthday string `json:"birthday,optional"`
}

type User struct {
	Name     string `json:"name"`
	Email    string `json:"email,optional"`
	Age      int    `json:"age"`
	Birthday string `json:"birthday,optional"`
}
